Task template
js-tasks-ru/htmlcss-20220317_goroshuk pull request #12
Opened 2022-04-05 20:44 UTC by DmitriiGoro

2022-04-05 20:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-06 18:25 UTC, GSemikozov requested changes

2022-04-06 18:25 UTC, GSemikozov commented on assets/css/main.css
> +@import '../../template.components/template.footer/footer.css';
футер и хедер для Главной и для страницы компонента - разные?

на самом деле это одни и те же компоненты, но с модификаторами. Соответственно они лежат в `components/header/header.css` и тд

2022-04-06 18:25 UTC, GSemikozov commented on pages/template.css
> +.main__inner {
общий комментарий - здесь набор классов, БЭМ не используется, а надо)

переиспользуем что уже должно быть - хедер, футер, пэйдж, контейнер, а то чего еще нет - оформляет как отдельные компоненты (сайдбар, превью компонента, общий для них враппер по типу main)

2022-04-07 15:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-08 11:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-08 11:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-08 15:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-09 13:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-09 13:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-09 16:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-10 10:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-10 11:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-11 14:34 UTC, DmitriiGoro commented on pages/template.css
> +.main__inner {
Готово

2022-04-11 14:34 UTC, DmitriiGoro commented on assets/css/main.css
> +@import '../../template.components/template.footer/footer.css';
Готово

2022-04-13 20:21 UTC, GSemikozov requested changes

2022-04-13 20:21 UTC, GSemikozov commented on components/header/_theme_grey/header.css
> +.header__logo {
если здесь определяем модификатор, тогда лого надо переложить в отдельное место)

2022-04-13 20:21 UTC, GSemikozov commented on components/page/_style_layout/page.css
> +.page_style_layout {
модификатор который делает все и сразу? Тогда может .page_inner (лэйаут для внутренней страницы)?

2022-04-13 20:21 UTC, GSemikozov commented on components/sidebar/sidebar.css
> +.sidebar__ul {
.sidebar__ul -> .sidebar__list

2022-04-13 20:21 UTC, GSemikozov commented on components/content/content.css
> +    margin-right: 39px;
точно надо? а то на уровне родителя уже есть grid-column-gap: 56px;

2022-04-16 10:06 UTC, DmitriiGoro commented on components/page/_style_layout/page.css
> +.page_style_layout {
Готово

2022-04-16 10:09 UTC, DmitriiGoro commented on components/sidebar/sidebar.css
> +.sidebar__ul {
Готово

2022-04-16 10:22 UTC, DmitriiGoro commented on components/content/content.css
> +    margin-right: 39px;
Готово
Да, он не обязателен

2022-04-16 10:29 UTC, DmitriiGoro commented on components/header/_theme_grey/header.css
> +.header__logo {
Если я правильно тебя понял, нужно создать отдельный стиль для лого, который лежит в модификаторе

Готово

2022-04-16 14:19 UTC, GSemikozov requested changes

2022-04-16 14:19 UTC, GSemikozov commented on components/header/_theme_grey/header.css
> +.header__logo_theme-grey {
.header_theme-grey .header__logo {}

2022-04-16 14:19 UTC, GSemikozov commented on pages/template.html
> +                <div class="content__wrapper">
это наверно все-таки __inner ) поскольку враппер - это то, что оборачивает, а иннер - то что внутри

2022-04-17 08:55 UTC, DmitriiGoro commented on pages/template.html
> +                <div class="content__wrapper">
Готово

2022-04-17 09:01 UTC, DmitriiGoro commented on components/header/_theme_grey/header.css
> +.header__logo_theme-grey {
Готово

Почему мы в данном случае используем комбинированный селектор, а не микс?

2022-04-17 11:22 UTC, GSemikozov commented on components/header/_theme_grey/header.css
> +.header__logo_theme-grey {
если бы лого был отдельным компонентом - применили бы микс

2022-04-17 11:24 UTC, GSemikozov approved these changes

2022-04-17 11:24 UTC, merged