task6-srcset
js-tasks-ru/htmlcss-20220317_goroshuk pull request #15
Opened 2022-04-11 14:33 UTC by DmitriiGoro

2022-04-11 14:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-11 15:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-12 10:53 UTC, GSemikozov requested changes

2022-04-12 10:53 UTC, GSemikozov commented on 06-lection4/03-srcset/index.html
> +            srcset="public/forest_400.jpg 2x, public/forest_768.jpg 4x">
1x + 2x )

2022-04-13 20:22 UTC, GSemikozov approved these changes

2022-04-13 20:22 UTC, merged