Task6 mobile page
js-tasks-ru/htmlcss-20220317_goroshuk pull request #16
Opened 2022-04-11 15:18 UTC by DmitriiGoro

2022-04-11 15:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-12 10:54 UTC, GSemikozov requested changes

2022-04-12 10:54 UTC, GSemikozov commented on components/card/card.css
> +    font-family: 'Inter';
указываем только те свойства, которые меняются

2022-04-12 10:54 UTC, GSemikozov commented on components/header/header.css
> +    font-family: 'Inter';
и тут

2022-04-12 19:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-12 19:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-12 19:46 UTC, DmitriiGoro commented on components/card/card.css
> +    font-family: 'Inter';
у карточек в desktop варианте шрифт Roboto, а в мобильной версии Inter (согласно макету)

2022-04-12 19:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-13 17:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-13 17:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-13 20:22 UTC, GSemikozov approved these changes

2022-04-13 20:22 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-04-13 20:24 UTC, GSemikozov approved these changes

2022-04-13 20:24 UTC, merged