page with burger
js-tasks-ru/htmlcss-20220317_goroshuk pull request #32
Opened 2022-04-27 12:01 UTC by DmitriiGoro

2022-04-27 12:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-30 10:29 UTC, GSemikozov requested changes

2022-04-30 10:29 UTC, GSemikozov commented on index.html
> +            <button class="burger-menu__opener" id="burger-menu-open">
это элемент хедера, не бургер меню

2022-04-30 10:29 UTC, GSemikozov commented on index.html
> +                <svg class="burger-menu__icon-opener" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
и это соответственно тоже

2022-04-30 10:29 UTC, GSemikozov commented on index.html
> +            <div class="container">
здесь контейнер будет лишним

2022-04-30 10:29 UTC, GSemikozov commented on index.html
> +                <a href="/index.html"><svg class="header__logo" width="110" height="32" viewBox="0 0 110 32" fill="none" xmlns="http://www.w3.org/2000/svg">
это уже будет не элемент хедера, а элемент меню. Но - можно лого сделать отдельным компонентом и тогда будет .logo

2022-05-01 15:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-04 19:50 UTC, GSemikozov requested changes

2022-05-04 19:50 UTC, GSemikozov commented on components/burger-menu/burger-menu.css
> +.burger-menu__opener, .burger-menu__closer {
.burger-menu__opener - осталось выпилить)

2022-05-05 08:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-05 20:53 UTC, GSemikozov approved these changes

2022-05-05 20:53 UTC, merged