Task3 button
js-tasks-ru/htmlcss-20220317_goroshuk pull request #4
Opened 2022-03-24 12:54 UTC by DmitriiGoro

2022-03-24 14:47 UTC, GSemikozov requested changes

2022-03-24 14:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
лучше pointer-events: none - так пользователь не сможет взаимодействовать с disabled кнопкой

2022-03-24 14:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 0;
по дизайну здесь иные отступы)

2022-03-24 14:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 0;
не хватает стилей для описания текста

2022-03-24 14:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__title_primary, .button_secondary {
.button__title - это лишний элемент, в нем нет необходимости

2022-03-24 14:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid transparent;
в secondary + primary цвет бордера должен совпадать с цветом фона

2022-03-24 14:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
транзишн можно задать сразу на уровне блока

2022-03-24 14:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
в том числе и чтобы не дублировать в каждом типе и для каждого состояния

2022-03-24 14:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
можно задать сразу на уровне .button

2022-03-24 14:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +[class*="button__title"] {
перенести в .button и удалить

2022-03-24 14:47 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +<<<<<<< HEAD
это незывается не зарезолвленные конфликты. Нужно в интерфейсе редактора правой кнопкой мыши - гит - резолв конфликтов - зарезолвить. Либо если уже помечено как resolved, то тогда руками удалить эти символы и оставить только актуальную версию

2022-03-25 07:15 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +    cursor: default;
Готово

2022-03-25 07:16 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +[class*="button__title"] {
Готово

2022-03-25 07:29 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
Готово

2022-03-25 07:31 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
Готово

2022-03-25 07:37 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +.button__title_primary, .button_secondary {
Готово

2022-03-25 07:46 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +    border: 1px solid transparent;
Готово

2022-03-25 09:27 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
`**transition: opacity 200ms ease-in-out, background 200ms ease-in-out;**` убрал в общий класс,
но конкретно для кнопки alternate поставил `**transition: opacity 200ms ease-in-out, BORDER 200ms ease-in-out;**` 
мне показалось это уместным

2022-03-25 09:34 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +    padding: 0;
Готово

2022-03-25 09:34 UTC, DmitriiGoro commented on 03-lection1/01-button/index.html
> +<<<<<<< HEAD
Готово. Удалил вручную

2022-03-25 11:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-25 19:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
ага

2022-03-25 19:40 UTC, GSemikozov requested changes

2022-03-25 19:40 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px;
а если снизу не 14px - текст вертикально нормально центрируется?

2022-03-25 19:40 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
не хватает font-family

2022-03-26 20:47 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
Готово. Добавил в Body

2022-03-26 20:48 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +    padding: 15px;
Да, к сожалению, текст в этом случае на 1px выше остальных. Сделал так, как посоветовали в Slack чате, через vertical-align.
Готово

2022-03-27 12:29 UTC, GSemikozov requested changes

2022-03-27 12:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
на body это конечно хорошо, но- нужно добавить и прямо здесь) поскольку шрифт наследуемое свойство, а на проекте их будет 3 - в итога можно отнаследоваться не от того шрифта, оторый по дизайну

2022-03-27 12:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +body {
общие стили задаются на уровне main.css и точне вне компонентов

2022-03-28 13:43 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
Готово

2022-03-28 13:43 UTC, DmitriiGoro commented on 03-lection1/01-button/button.css
> +body {
Готово

2022-03-28 15:42 UTC, GSemikozov approved these changes

2022-03-28 15:43 UTC, merged