Task3 accordion
js-tasks-ru/htmlcss-20220317_goroshuk pull request #5
Opened 2022-03-25 19:24 UTC by DmitriiGoro

2022-03-25 19:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-25 19:43 UTC, GSemikozov requested changes

2022-03-25 19:43 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
жестко фиксировать ширину не стоит - на мобилке сразу станет плохо

2022-03-25 19:43 UTC, GSemikozov commented on assets/css/main.css
> +    /* font-family: 'Roboto', sans-serif; */
правильнее будет задать этот шрифт просто на body)

2022-03-25 19:43 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-left: 32px;
чтобы не задавать на каждом дочернем элементе .accordion__item-а одинаковые марджины, лучше один раз задать паддинги на уровне родителя и не заморачиваться с марджинами у дочерних элементов

2022-03-25 19:43 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__:last-child {
.accordion__ -> .accordion__item?

2022-03-25 19:43 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item:last-child {
дубль?

2022-03-26 18:54 UTC, DmitriiGoro commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
Готово

2022-03-26 18:56 UTC, DmitriiGoro commented on assets/css/main.css
> +    /* font-family: 'Roboto', sans-serif; */
Готово

2022-03-26 20:11 UTC, DmitriiGoro commented on 03-lection1/02-accordion/accordion.css
> +    margin-left: 32px;
Готово. 

Единственное, я добавил padding-bottom: 32px для атрибута open и обнулил margin-bottom у accordion__text

2022-03-26 20:11 UTC, DmitriiGoro commented on 03-lection1/02-accordion/accordion.css
> +.accordion__:last-child {
Готово. Невнимательно проверил

2022-03-26 20:11 UTC, DmitriiGoro commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item:last-child {
Готово

2022-03-26 20:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-26 20:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-27 12:30 UTC, GSemikozov requested changes

2022-03-27 12:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +body {
задается глобально, не в компоненте

2022-03-27 12:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 60vw;
удалим

2022-03-28 13:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-28 13:45 UTC, DmitriiGoro commented on 03-lection1/02-accordion/accordion.css
> +body {
Готово

2022-03-28 13:45 UTC, DmitriiGoro commented on 03-lection1/02-accordion/accordion.css
> +    width: 60vw;
Готово

2022-03-28 13:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-28 15:43 UTC, GSemikozov submitted a review, later dismissed

2022-03-28 15:43 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-03-28 20:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-31 14:56 UTC, GSemikozov requested changes

2022-03-31 14:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    height: 24px;
будет лишним

2022-03-31 14:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-left: 32px;
справа тоже нужен (в будущем там будет иконка и она не должна прижиматься к правой границе)

2022-04-01 12:20 UTC, DmitriiGoro commented on 03-lection1/02-accordion/accordion.css
> +    height: 24px;
готово

2022-04-01 12:20 UTC, DmitriiGoro commented on 03-lection1/02-accordion/accordion.css
> +    padding-left: 32px;
готово

2022-04-01 19:59 UTC, GSemikozov approved these changes

2022-04-01 19:59 UTC, merged