Task page
js-tasks-ru/htmlcss-20220317_goroshuk pull request #6
Opened 2022-03-29 19:41 UTC by DmitriiGoro

2022-03-29 19:46 UTC, GSemikozov requested changes

2022-03-29 19:46 UTC, GSemikozov commented on components/container/container.css
> +[class*=container] {
просто .container

2022-03-29 19:46 UTC, GSemikozov commented on components/container/container.css
> +.container_logo {
это лишнее, лого - элемент хедера, а не модификатор контейнера)

2022-03-29 19:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-30 18:27 UTC, DmitriiGoro commented on components/container/container.css
> +[class*=container] {
Готово

2022-03-30 18:27 UTC, DmitriiGoro commented on components/container/container.css
> +.container_logo {
Готово

2022-03-30 19:05 UTC, GSemikozov requested changes

2022-03-30 19:05 UTC, GSemikozov commented on components/container/container.css
> +.container_logo {
нет, не готово, не вижу изменений)

2022-03-30 19:21 UTC, DmitriiGoro commented on components/container/container.css
> +.container_logo {
Теперь готово )

2022-03-31 14:37 UTC, GSemikozov requested changes

2022-03-31 14:37 UTC, GSemikozov commented on index.html
> +                <svg class="header__logo logo" width="110" height="32" viewBox="0 0 110 32" fill="none" xmlns="http://www.w3.org/2000/svg">
logo? видимо лишний класс?)

2022-03-31 14:37 UTC, GSemikozov commented on index.html
> +            <h1 class="header__title title">Reusable component library</h1>
тут лишний title

2022-03-31 14:37 UTC, GSemikozov commented on index.html
> +                <h2 class="footer__title title">About</h2>
и тут

2022-03-31 14:40 UTC, DmitriiGoro commented on index.html
> +                <svg class="header__logo logo" width="110" height="32" viewBox="0 0 110 32" fill="none" xmlns="http://www.w3.org/2000/svg">
Логика моя была в том, что logo, как и title ниже, могут использоваться в качестве готового блока в других местах (в теории), поэтому, чтобы не сбивать их стили, я добавил основной блок и элемент блока. 
Или в нашем проекте это лишнее?

2022-04-03 18:59 UTC, GSemikozov requested changes

2022-04-03 18:59 UTC, GSemikozov commented on assets/fonts/fonts.css
> +<<<<<<< HEAD
не исправленный конфликт

2022-04-03 18:59 UTC, GSemikozov commented on components/header/header.css
> +<<<<<<< HEAD
неисправленный конфликт

2022-04-03 19:10 UTC, GSemikozov approved these changes

2022-04-03 19:11 UTC, merged